language: julia
os:
    - linux
julia:
    - 1.4
    - 1.5
    - nightly
env:
  - JULIA_PROJECT="@."
notifications:
    email: false
after_success:
  - julia -e '(ENV["TRAVIS_JULIA_VERSION"] != "1.5" || ENV["TRAVIS_OS_NAME"] != "linux") && exit(); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
jobs:
  allow_failures:
    - julia: nightly
